name: 'Setup environment'
description: 'Sets up analyzers, CodeChecker and Bazel'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set bazel version to 6.5.0
      run: echo "6.5.0" > .bazelversion

    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install CodeChecker analyzers
      run: |
        sudo apt-get update --quiet
        sudo apt-get install --no-install-recommends \
          clang \
          clang-tools \
          clang-tidy

    - name: Install CodeChecker
      run: pip3 install codechecker
  outputs:
    setup_complete: true