name: codechecker-bazel-tests-2

# Triggers the workflow on push or pull request events.
on: [pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  small_test:
    name: Small Project Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository # needed for install-deps.sh
        uses: actions/checkout@v4

      - name: Set bazel version to 6.5.0
        run: echo "6.5.0" > .bazelversion

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install CodeChecker analyzers
        run: sh .github/workflows/install-deps.sh

      - name: Install CodeChecker
        run: pip3 install codechecker

      - name: Checkout yaml-cpp
        run:  |
          git clone --recurse-submodules https://github.com/jbeder/yaml-cpp.git
          cd yaml-cpp
          git checkout yaml-cpp-0.7.0
          echo "6.5.0" > .bazelversion

      - name: Patch yaml-cpp
        run: |
          cd yaml-cpp
          echo "#-------------------------------------------------------" >> BUILD.bazel
          echo "" >> BUILD.bazel
          echo "# codechecker rules" >> BUILD.bazel
          echo "load(" >> BUILD.bazel
          echo "    \"@bazel_codechecker//src:codechecker.bzl\"," >> BUILD.bazel
          echo "    \"codechecker_test\"," >> BUILD.bazel
          echo ")" >> BUILD.bazel
          echo "load(" >> BUILD.bazel
          echo "    \"@bazel_codechecker//src:code_checker.bzl\"," >> BUILD.bazel
          echo "    \"code_checker_test\"," >> BUILD.bazel
          echo ")" >> BUILD.bazel
          echo "" >> BUILD.bazel
          echo "codechecker_test(" >> BUILD.bazel
          echo "    name = \"codechecker_test_yaml-cpp\"," >> BUILD.bazel
          echo "    targets = [" >> BUILD.bazel
          echo "        \":yaml-cpp\"," >> BUILD.bazel
          echo "    ]," >> BUILD.bazel
          echo ")" >> BUILD.bazel
          echo "" >> BUILD.bazel
          echo "code_checker_test(" >> BUILD.bazel
          echo "    name = \"code_checker_test_yaml-cpp\"," >> BUILD.bazel
          echo "    targets = [" >> BUILD.bazel
          echo "        \":yaml-cpp\"," >> BUILD.bazel
          echo "    ]," >> BUILD.bazel
          echo ")" >> BUILD.bazel
          echo "" >> BUILD.bazel
          echo "#-------------------------------------------------------" >> BUILD.bazel
          cat BUILD.bazel
            
      - name: Patch WORKSPACE
        run: |
          cd yaml-cpp
          echo "#----------------------------------------------------" >> WORKSPACE
          echo "" >> WORKSPACE
          echo "load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")" >> WORKSPACE
          echo "" >> WORKSPACE
          echo "git_repository(" >> WORKSPACE
          echo "    name = "bazel_codechecker"," >> WORKSPACE
          echo "    remote = \"https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git\"," >> WORKSPACE
          echo "    branch = \"${{ github.event.pull_request.head.ref }}\"," >> WORKSPACE
          echo ")" >> WORKSPACE
          echo "" >> WORKSPACE
          echo "load(" >> WORKSPACE
          echo "    "@bazel_codechecker//src:tools.bzl"," >> WORKSPACE
          echo "    "register_default_codechecker"," >> WORKSPACE
          echo "    "register_default_python_toolchain"," >> WORKSPACE
          echo ")" >> WORKSPACE
          echo "" >> WORKSPACE
          echo "register_default_python_toolchain()" >> WORKSPACE
          echo "register_default_codechecker()" >> WORKSPACE
          echo "" >> WORKSPACE
          echo "#----------------------------------------------------" >> WORKSPACE
          cat WORKSPACE

      - name: Run Bazel CodeChecker
        run: |
          cd yaml-cpp
          bazel build :codechecker_test_yaml-cpp


