name: codechecker-bazel-tests-2

# Triggers the workflow on push or pull request events.
on: [pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  small_test:
    name: Small Project Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository # needed for install-deps.sh
        uses: actions/checkout@v4

      - name: Set bazel version to 6.5.0
        run: echo "6.5.0" > .bazelversion

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install CodeChecker analyzers
        run: sh .github/workflows/install-deps.sh

      - name: Install CodeChecker
        run: pip3 install codechecker

      - name: Patch yaml-cpp
        run:  |
          sh .github/workflows/patch-test-proj.sh ${{ github.event.pull_request.head.repo.full_name }} ${{ github.event.pull_request.head.ref }}
          cat yaml-cpp/BUILD.bazel
          cat yaml-cpp/WORKSPACE

      - name: Run Bazel CodeChecker
        run: |
          cd yaml-cpp
          bazel build :codechecker_test_yaml-cpp


